services:
  site:
    image: jekyll/jekyll:4
    working_dir: /srv/jekyll
    platform: linux/amd64
    command: >
      sh -c "bundle install &&
             bundle exec jekyll serve --host 0.0.0.0 --port 4000 --livereload --force_polling"
    ports:
      - "4000:4000"
      - "35729:35729"
    environment:
      JEKYLL_ENV: development
      BUNDLE_PATH: /usr/local/bundle
    volumes:
      - .:/srv/jekyll
      - bundle:/usr/local/bundle

volumes:
  bundle:
